import { Product } from "./types";

export const products: Product[] = [
  {

    //skincare Products
    id: "sk-001",
    name: "Cosrx Cleanser",
    category: "Skincare",
    price: 1000,
    image: "/images/cosrxcleanser.jpg",
    description: "A potent overnight serum with retinol and peptides to renew skin texture while you sleep.",
    isNew: true,
    isBestSeller: true,
    dateAdded: "2026-06-20",
    rating: 4.8,
    stock: 24,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
    
  },
  {
    id: "sk-002",
    name: "Salicylic Cleanser",
    category: "Skincare",
    price: 1800,
    image: "/images/salysilic.jpg",
    description: "Rosewater-infused mist that hydrates and sets makeup with a dewy finish.",
    isNew: false,
    isBestSeller: true,
    dateAdded: "2026-03-11",
    rating: 4.6,
    stock: 40,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "sk-003",
    name: "Dr.Rashel Aloe Cleanser",
    category: "Skincare",
    price: 3500,
    image: "/images/rashelaloecleanser.jpg",
    description: "20% Vitamin C concentrate that fades dark spots and evens skin tone.",
    isNew: true,
    isBestSeller: false,
    dateAdded: "2026-07-01",
    rating: 4.7,
    stock: 18,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "sk-004",
    name: "Dr.Rashel Vit c cleanser",
    category: "Skincare",
    price: 2400,
    image: "/images/rashelvitc.jpg",
    description: "French pink clay mask that draws out impurities without over-drying.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-11-02",
    rating: 4.4,
    stock: 33,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "sk-005",
    name: "Cosrx Starter Set",
    category: "Skincare",
    price: 4500,
    image: "/images/CosrxKit1.jpg",
    description: "Cosrx Starter Kit for begginer skincare routine",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-11-02",
    rating: 4.4,
    stock: 33,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  
  {
    id: "sk-006",
    name: "The Ordinary Set",
    category: "Skincare",
    price: 2400,
    image: "/images/TheOrdinaryProducts.jpg",
    description: "French pink clay mask that draws out impurities without over-drying.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-11-02",
    rating: 4.4,
    stock: 33,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "sk-007",
    name: "Dr.Rashel Vitamin C Set",
    category: "Skincare",
    price: 2600,
    image: "/images/rashelset1.jpg",
    description: "French pink clay mask that draws out impurities without over-drying.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-11-02",
    rating: 4.4,
    stock: 33,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "sk-008",
    name: "Simple Set",
    category: "Skincare",
    price: 2400,
    image: "/images/Simpleset1.jpg",
    description: "French pink clay mask that draws out impurities without over-drying.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-11-02",
    rating: 4.4,
    stock: 33,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "sk-009",
    name: "The Ordinary Moisturizing Factor",
    category: "Skincare",
    price: 2400,
    image: "/images/Ordinarymoisturizer.jpg",
    description: "French pink clay mask that draws out impurities without over-drying.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-11-02",
    rating: 4.4,
    stock: 33,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "sk-010",
    name: "Simple Moisturizer",
    category: "Skincare",
    price: 2400,
    image: "/images/simplemoisturizer.jpg",
    description: "French pink clay mask that draws out impurities without over-drying.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-11-02",
    rating: 4.4,
    stock: 33,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "sk-011",
    name: "Simple Face Wash",
    category: "Skincare",
    price: 2400,
    image: "/images/facewash1.jpg",
    description: "French pink clay mask that draws out impurities without over-drying.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-11-02",
    rating: 4.4,
    stock: 33,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "sk-012",
    name: "Athea Cream",
    category: "Skincare",
    price: 2400,
    image: "/images/Atheacream1.jpg",
    description: "French pink clay mask that draws out impurities without over-drying.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-11-02",
    rating: 4.4,
    stock: 33,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "sk-013",
    name: "Simple Toner",
    category: "Skincare",
    price: 2400,
    image: "/images/simpletoner1.jpg",
    description: "French pink clay mask that draws out impurities without over-drying.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-11-02",
    rating: 4.4,
    stock: 33,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "sk-014",
    name: "The Ordinary Glycolic Toner",
    category: "Skincare",
    price: 800,
    image: "/images/glycolictoner.jpg",
    description: "French pink clay mask that draws out impurities without over-drying.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-11-02",
    rating: 4.4,
    stock: 33,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "sk-015",
    name: "Medicube Set",
    category: "Skincare",
    price: 3500,
    image: "/images/medicubeset.jpg",
    description: "French pink clay mask that draws out impurities without over-drying.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-11-02",
    rating: 4.4,
    stock: 33,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },


  //haircare products
  {
    id: "hc-001",
    name: "Mielle Masque",
    category: "Haircare",
    price: 2900,
    image: "/images/masquemielle.jpg",
    description: "Lightweight argan oil blend that tames frizz and restores shine.",
    isNew: false,
    isBestSeller: true,
    dateAdded: "2025-09-14",
    rating: 4.9,
    stock: 27,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "hc-002",
    name: "Mielle Shampoo & Conditioner",
    category: "Haircare",
    price: 2100,
    image: "/images/mielleshacon.jpg",
    description: "Sulfate-free shampoo formulated with silk proteins for damaged hair.",
    isNew: true,
    isBestSeller: false,
    dateAdded: "2026-06-28",
    rating: 4.5,
    stock: 50,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "hc-003",
    name: "Batana Cream",
    category: "Haircare",
    price: 3300,
    image: "/images/batanacondition.jpg",
    description: "A leave-in scalp treatment that soothes and stimulates healthy growth.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-12-19",
    rating: 4.3,
    stock: 21,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "hc-004",
    name: "Batana oil",
    category: "Haircare",
    price: 3300,
    image: "/images/batanaoil.jpg",
    description: "A leave-in scalp treatment that soothes and stimulates healthy growth.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-12-19",
    rating: 4.3,
    stock: 21,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
{
    id: "hc-008",
    name: "SoftnFree Cream",
    category: "Haircare",
    price: 3300,
    image: "/images/softnfreegreen.jpg",
    description: "A leave-in scalp treatment that soothes and stimulates healthy growth.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-12-19",
    rating: 4.3,
    stock: 21,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "hc-005",
    name: "Cantu Orange Cream",
    category: "Haircare",
    price: 3300,
    image: "/images/cantuconditioner.jpg",
    description: "A leave-in scalp treatment that soothes and stimulates healthy growth.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-12-19",
    rating: 4.3,
    stock: 21,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  
  {
    id: "hc-006",
    name: "7 Days Serum",
    category: "Haircare",
    price: 3300,
    image: "/images/7days.jpg",
    description: "A leave-in scalp treatment that soothes and stimulates healthy growth.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-12-19",
    rating: 4.3,
    stock: 21,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },

{
    id: "hc-007",
    name: "ORS Olive Moussee",
    category: "Haircare",
    price: 3300,
    image: "/images/olivemousseeors.jpg",
    description: "A leave-in scalp treatment that soothes and stimulates healthy growth.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-12-19",
    rating: 4.3,
    stock: 21,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },

  //makeup products
  {
    id: "mk-001",
    name: "Satin Matte Liquid Lipstick — Noir Rouge",
    category: "Makeup",
    price: 2600,
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80",
    description: "Long-wear liquid lipstick with a weightless satin-matte finish.",
    isNew: false,
    isBestSeller: true,
    dateAdded: "2025-08-05",
    rating: 4.7,
    stock: 60,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "mk-002",
    name: "Second Skin Foundation",
    category: "Makeup",
    price: 4800,
    image: "https://images.unsplash.com/photo-1631730359585-38a4935cbec4?w=800&q=80",
    description: "Buildable, breathable foundation with 24-hour hydration and natural finish.",
    isNew: true,
    isBestSeller: true,
    dateAdded: "2026-07-05",
    rating: 4.8,
    stock: 15,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "mk-003",
    name: "Sculpt & Glow Highlight Palette",
    category: "Makeup",
    price: 3900,
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&q=80",
    description: "A four-shade contour and highlight palette for a natural, lit-from-within glow.",
    isNew: false,
    isBestSeller: false,
    dateAdded: "2025-10-22",
    rating: 4.5,
    stock: 29,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "mk-004",
    name: "Feline Precision Eyeliner",
    category: "Makeup",
    price: 1500,
    image: "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=800&q=80",
    description: "Ultra-fine tip liner for a precise winged look that lasts all day.",
    isNew: true,
    isBestSeller: false,
    dateAdded: "2026-06-30",
    rating: 4.6,
    stock: 45,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "fr-001",
    name: "Noire Oud — Eau de Parfum",
    category: "Fragrance",
    price: 8500,
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80",
    description: "A deep, smoky oud fragrance layered with amber and dark rose.",
    isNew: false,
    isBestSeller: true,
    dateAdded: "2025-07-18",
    rating: 4.9,
    stock: 12,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "fr-002",
    name: "Bloom & Bergamot Eau de Toilette",
    category: "Fragrance",
    price: 6200,
    image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=800&q=80",
    description: "A bright, citrus-forward scent with white floral heart notes.",
    isNew: true,
    isBestSeller: false,
    dateAdded: "2026-07-10",
    rating: 4.4,
    stock: 22,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
  {
    id: "fr-003",
    name: "Velvet Vanilla Body Mist",
    category: "Fragrance",
    price: 2200,
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&q=80",
    description: "A soft, gourmand body mist with vanilla, musk, and tonka bean.",
    isNew: false,
    isBestSeller: true,
    dateAdded: "2025-05-30",
    rating: 4.6,
    stock: 55,
    brand: "Cosrx",    
    subcategory: "Toner",
    concerns: [
    "Dry Skin",
    "Sensitive Skin"
  ],
  },
];

export const categories: Product["category"][] = ["Skincare", "Haircare", "Makeup", "Fragrance"];
